config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'expenses/index'
  root to: "expenses#index"
  resources :wishlists
  resources :details
  resources :expenses
  resources :charts, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '__' },
    { id: 2, name: '食費'},
    { id: 3, name: '日用品'},
    { id: 4, name: '美容・衣料品'},
    { id: 5, name: '教養'},
    { id: 6, name: '交際費'},
    { id: 7, name: '医療費'},
    { id: 8, name: '交通費'},
    { id: 9, name: '通信費'},
    { id: 10, name: '水道・光熱費'},
    { id: 11, name: '家関係'},
    { id: 12, name: '税金'},
    { id: 13, name: '趣味'},
    { id: 14, name: '大きな出費'},
    { id: 15, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :details, foreign_key: :name

end

app/models/detail.rb
class Detail < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :incomes_or_expenses
  belongs_to :category
  belongs_to :payment_methods
  belongs_to :number_of_time
  belongs_to :user
  
    validates :price,               numericality: {with: /\A[0-9]+\z/, message: 'Half-width number'}

  with_options presence: true do
    validates :price
    validates :item_name
    validates :day

    with_options numericality: { other_than: 1 , message: 'Select'} do
      validates :incomes_or_expenses_id
      validates :category_id
      validates :payment_methods_id
      validates :number_of_time_id
    end

  end
  
  def start_time
    self.day
  end
end

app/models/incomes_or_expenses.rb
class IncomesOrExpenses < ActiveHash::Base
  self.data = [
    { id: 1, name: '__' },
    { id: 2, name: '収入' },
    { id: 3, name: '支出' }
  ]

  include ActiveHash::Associations
  has_many :details

end

app/models/number_of_time.rb
class NumberOfTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '__'},
    { id: 2, name: '1'},
    { id: 3, name: '2'},
    { id: 4, name: '3'},
    { id: 5, name: '5'},
    { id: 6, name: '6'},
    { id: 7, name: '10'},
    { id: 8, name: '12'},
    { id: 9, name: '15'},
    { id: 10, name: '18'},
    { id: 11, name: '20'},
    { id: 12, name: '24'},
    { id: 13, name: '30'},
    { id: 14, name: '36'},
    { id: 15, name: 'ボーナス1回'},
    { id: 16, name: 'ボーナス2回'},

  ]
  include ActiveHash::Associations
  has_many :details

end

app/models/payment_methods.rb
class PaymentMethods < ActiveHash::Base
  self.data = [
    { id: 1, name: '__' },
    { id: 2, name: '現金'},
    { id: 3, name: 'カード'}
  ]

  include ActiveHash::Associations
  has_many :details
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wishlists
  has_many :details

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i, message: 'Include both letters and numbers' }
  end

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

  belongs_to :user
  has_one_attached :image
  
  with_options presence: true do
    validates :price
    validates :name
    validates :image
  end
    validates :price, numericality: {with: /\A[0-9]+\z/, message: 'Half-width number'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @detail = Detail.new
    @details = Detail.all
    @sum_of_expenses = Detail.where(incomes_or_expenses_id: 3).sum(:price)
    @price = Detail.where(incomes_or_expenses_id: 3).group(:category_id).sum(:price)
  end

  def show
    @detail = Detail.find(params[:id])
  end
  
  def update
    @detail = Detail.find(params[:id])
  end

  def destroy
    @detail = Detail.find(params[:id])
  end

  private
  def detail_params
    params.require(:detail).permit(:item_name, :memo, :incomes_or_expenses_id, :category_id, :day, :price, :payment_methods_id, :number_of_time_id).merge(user_id: current_user.id)
  end

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: [:show, :edit]
  def index
    @details = Detail.all

  end

  def new
    @detail = Detail.new 
  end

  def create
    @detail = Detail.new(detail_params)
    if @detail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    detail = Detail.find(params[:id])
    detail.update(detail_params)
    if detail.save
      redirect_to detail_path
    else
      render :index
    end
  end

  def destroy
    detail = Detail.find(params[:id])
    detail.destroy
    if detail.delete
      redirect_to root_path(@detail)
    else
      render :edit
    end
  end

  

  private
  def detail_params
    params.require(:detail).permit(:item_name, :memo, :incomes_or_expenses_id, :category_id, :day, :price, :payment_methods_id, :number_of_time_id).merge(user_id: current_user.id)
  end

  def set_expense
    @detail = Detail.find(params[:id])
  end


end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @details = Detail.all

    time = Time.now
    this_month = time.month
    this_year = time.year

    @income_total = Detail.where(incomes_or_expenses_id: '2').group("Year(created_at)").group("Month(created_at)").sum(:price)
    @expense_total = Detail.where(incomes_or_expenses_id: '3').group("Year(created_at)").group("Month(created_at)").sum(:price)

  end

  private
  def detail_params
    params.require(:detail).permit(:item_name, :memo, :incomes_or_expenses_id, :category_id, :day, :price, :payment_methods_id, :number_of_time_id).merge(user_id: current_user.id)
  end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:edit, :show,]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @wishlists = Wishlist.all
  end

  def new
    @wishlist = Wishlist.new
    @wishlists = Wishlist.all
  end

  def create
    @wishlist = Wishlist.new(wishlist_params)
    if @wishlist.save
      redirect_to root_path
    else
      render :index
    end
  end

  def show
    
  end

  def edit
  end
  
  def update
    wishlist = Wishlist.find(params[:id])
    wishlist.update(wishlist_params)
    if wishlist.save
      redirect_to wishlist_path
    else
      render :index
    end
  end

  def destroy
    wishlist = Wishlist.find(params[:id])
    wishlist.destroy
    if wishlist.delete
      redirect_to root_path(@wishlist)
    else
      render :edit
    end
  end


  private
  def wishlist_params
    params.require(:wishlist).permit(:name, :price, :image, :memo).merge(user_id: current_user.id)
  end

  def set_wishlist
    @wishlist = Wishlist.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/charts/index.html.erb
<main class="main">
  <div class="inner">
    <div style="text-align:center;">
      <div class="card__wrapper"> 
      <h1>IncomesAndExpenses</h1>
        <%= pie_chart @price, library: {title: {text: "支出<br> ¥#{@sum_of_expenses.to_s(:delimited)}"}} %>
    </div>
  </div>
</main>

app/views/details/_detail.html.erb
<div class="card">
  <%= link_to details_path, method: :get do %>
    <%= image_tag wishlist.image.variant(resize: '300x300'), class: :card__img if wishlist.image.attached? %>
  <% end %>
  <div class="card__body">
    <%= link_to detail.item_name, detail_path(detail.id), method: :get, class: :card__title %>
    <p class="card__summary">
      <%= derail.memo %>
    </p>
    <p class="card__summary">
      ¥<%= derail.price %>
    </p>
    <%= link_to "by#{current_user.nickname}", root_path, class: :card__user %>
  </div>
</div>

app/views/details/_form.html.erb
<%= form_with(model: @detail, local: true) do |f| %>
  <div class="field">
    <%= f.label :item_name, "項目" %><br />
    <%= f.text_field :item_name, id:"item_name" %>
  </div>

  <div class="field">
    <%= f.label :memo, "メモ" %><br />
    <%= f.text_area :memo, class: :form_text, id:"memo" %>
  </div>

  <div class="field">
    <%= f.label :incomes_or_expenses, "収支" %><br />
    <%= f.collection_select(:incomes_or_expenses_id, IncomesOrExpenses.all, :id, :name, {},{class:"select-box", id:"inocomes_or_expenses"}) %>
  </div>

  <div class="field">
    <%= f.label :category, "カテゴリー" %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {},{class:"select-box", id:"category"}) %>
  </div>

  <div class="field">
    <%= f.label :day, "日にち" %><br />
    <%= f.date_field :day, id:"day" %>
  </div>

  <div class="field">
    <%= f.label :price, "値段" %><br />
    <%= f.text_field :price, id: "price"%>
  </div>

  <div class="field">
    <%= f.label :payment_methods, "支払い方法" %><br />
    <%= f.collection_select(:payment_methods_id, PaymentMethods.all, :id, :name, {},{class:"select-box", id:"payment_methods"}) %>
  </div>

  <div class="field">
    <%= f.label :number_of_time, "支払い回数" %><br />
    <%= f.collection_select(:number_of_time_id, NumberOfTime.all, :id, :name, {},{class:"select-box", id:"number_of_times"}) %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form_btn %>
  </div>
<% end %>

app/views/details/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">詳細変更</h2>
      <%= render "details/form" %>
    </div>
  </div>
</div>

app/views/details/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
     <%= link_to image_tag("k-logo.png", class: :logo) %>
      <h2 class="page-heading"></h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render "details/form" %>
    </div>
  </div>
</div>

app/views/details/show.html.erb
<main class="main">
  <div class="inner">
    <div class="box24">
        <div class="wishlist__manage">
          <%= link_to "編集する", edit_detail_path(@detail.id), method: :get, class: :wishlist__btn %>
          <%= link_to "削除する", detail_path(@detail.id), method: :delete, class: :wishlist__btn %>
        </div>


      <p class="wishlist__hedding">
        <%= @detail.item_name%>
      </p>

      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>

      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      
      <div class="wishlist__body">
        <div class="wishlist__detail">
          <div class="detail__title"> ¥<%= @detail.price %>
          </div>
        </div>
        <div class="wishlist__detail">
          <p class="detail__title">memo</p>
          <p class="detail__message">
            <%= @detail.memo %>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/expenses/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        ▽<%= link_to "#{current_user.nickname}さん", root_path, class: :greeting__link%>
      </div>
    <% end %>
    
    <div class="box1">
      <div style="text-align:center;">
          <%= link_to image_tag("wishlist-icon.png", class: :wish_logo), wishlists_path, method: :get %>
          <%= link_to image_tag("kiroku-icon.png", class: :wish_logo), new_detail_path, method: :get %>
          <%= link_to image_tag("ichiran-icon.png",class: :wish_logo), charts_path, method: :get %>
      </div>
    </div>

            <div style="text-align:center;">
               <%= "収入 : #{@income_total.values.to_s(:delimited) }" %>　　
               <%= "支出 : #{@expense_total.values.to_s(:delimited)}"%>
            </div>
    <div>
        <%= month_calendar events: @details do |date, details| %>
          <%= date.day %>
            <% details.each do |detail| %>
              <%= link_to detail_path(detail.id), method: :get, class: :card__summary do %>
                <% if detail.incomes_or_expenses_id == 3 %>
                  <div>
                    <span style="color:#ff0000;"><%= "-#{detail.price.to_s(:delimited)}" %>
                  </div>
                <% else %>
                  <div>
                  <%= detail.price.to_s(:delimited) %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
        <% end %>
      </div>

    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
    </div>
  </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>mmm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wishlists/_form.html.erb
<%= form_with(model: @wishlist, local: true) do |f|%>
  <div class="field">
    <%= f.label :name, "行きたいところ欲しいもの" %><br />
    <%= f.text_field :name, id:"wishlist_name" %>
  </div>

  <div class="field">
    <%= f.label :price, "プライス" %><br />
    <%= f.text_field :price, class: :form__text, id:"wishlist_price" %>
  </div>

  <div class="field">
    <%= f.label :memo, "メモ" %><br />
    <%= f.text_area :memo, class: :form__text, id:"wishlist_memo" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"wishlist_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/wishlists/_wishlist.html.erb
<div class="card">
  <%= link_to wishlists_path, method: :get do %>
    <%= image_tag wishlist.image.variant(resize: '300x300'), class: :card__img if wishlist.image.attached? %>
  <% end %>
  <div class="card__body">
    <%= link_to wishlist.name, wishlist_path(wishlist.id), method: :get, class: :card__title %>
    <p class="card__summary">
      <%= wishlist.memo %>
    </p>
    <p class="card__summary">
      ¥<%= wishlist.price %>
    </p>
    <%= link_to "by#{current_user.nickname}", root_path, class: :card__user %>
  </div>
</div>

app/views/wishlists/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ﾖｸﾎﾞｳﾘｽﾄ編集</h2>
      <%= render "wishlists/form" %>
    </div>
  </div>
</div>

app/views/wishlists/index.html.erb
<main class="main">
  <div class="inner">
    <div class="post_btn">
      <%= link_to image_tag("y-logo.png", class: :logo), new_wishlist_path, method: :get %>
    </div>
    <div class="card__wrapper">
      <%= render partial: "wishlists/wishlist" , collection: @wishlists %>
    </div>
  </div>
</main>

app/views/wishlists/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
     <%= link_to image_tag("y-logo.png", class: :logo) %>
      <h2 class="page-heading"></h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render "wishlists/form" %>
    </div>
  </div>
</div>

app/views/wishlists/show.html.erb
<main class="main">
  <div class="inner">
    <div class="wishlist__wrapper">
      <p class="wishlist__hedding">
        <%= @wishlist.name%>
      </p>
      <%= link_to "by #{@wishlist.user.nickname}", root_path, class: :wishlist__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="wishlist__manage">
          <%= link_to "編集する", edit_wishlist_path(@wishlist.id), method: :get, class: :wishlist__btn %>
          <%= link_to "削除する", wishlist_path(@wishlist.id), method: :delete, class: :wishlist__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="wishlist__image">
        <%= image_tag @wishlist.image, class: :card__img if @wishlist.image.attached? %>
      </div>
      <div class="wishlist__body">
        <div class="wishlist__detail">
          <p class="detail__title">price</p>
          <p class="detail__message">
            ¥<%= @wishlist.price %>
          </p>
        </div>
        <div class="wishlist__detail">
          <p class="detail__title">memo</p>
          <p class="detail__message">
            <%= @wishlist.memo %>
          </p>
        </div>
      </div>
      <div class="wishlist__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%# <%= form_with model: モデル名,local: true do |f|%>
            <div class="field">
              <%# <%= f.label :hoge, "コメント" %><br />
              <%# <%= f.text_field :hoge, id:"comment_text" %>
            </div>
            <div class="actions">
              <%# <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <%# <% end %> 
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <%# <%= " コメントのテキスト "%>
              <%# <%= link_to "（ ユーザー名 ）", root_path, class: :comment_user %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>